# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  opagent

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'
- task: Bash@3
  displayName: 'Update Version'
  inputs:
    targetType: 'inline'
    script: |
          echo "Current Version: $(versionNumber)"
          npm --no-git-tag-version version $(versionNumber) --allow-same-version

- script: |
    npm install
  displayName: 'npm install and build'
- script: npm publish
  displayName: publish the package